### ISSUE TITLE
Make the project ready to be a public repo

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/engage-2#12]
I think we should check for sensitive data in the repository. In particular we should check whether any of the mocked data for the frontend is sensitive.

If anything sensitive is found we need to remove it and probably squash a bunch of commits, so the sooner this happens (or at least gets checked) the better.

**Comment by jandix** [comment]
@KonradUdoHannes @DatenBergwerker can we close this issue?

**Comment by KonradUdoHannes** [comment]
@jandix yes, since the repo is already public it was hopefully also ready for that 😂
