### ISSUE TITLE
set poetry version to >=1.5

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/engage-2#45]
This should involve recommending this version in the readme and setting it in github actions and docker containers

**Comment by jandix** [comment]
See https://github.com/CorrelAid/engage-2/pull/42/files#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486

**Comment by jandix** [comment]
Version has been updated to 1.5.1: https://github.com/CorrelAid/engage-2/blob/development/backend/Dockerfile#L3
